### ISSUE TITLE
Faute orthographe libellé

### ISSUE THREAD

**Issue by elouanduval** [SuperPingPong/score.pingsmash.fr#1]
Il y a une faute sur le libellé "Licence", actuellement c'est "License" et ça devrait être un C à la place du S = Licence.

https://github.com/SuperPingPong/score.pingsmash.fr/blob/d61c43e6d6bff09565b0344c8dd0dfc16ae65528/frontend/html/index.html#L75C47-L75C54

**Comment by zteeed** [comment]
Mise à jour ok: https://score.pingsmash.fr
